
module.exports = {
  API_BASE_URL: process.env.REACT_APP_API_BASE_URL,
  COMPANY_NAME: process.env.REACT_APP_RAZORPAY_CLIENT_NAME,
  FREE_PLAN_ID: process.env.REACT_APP_FREE_PLAN_ID,
  GTM_ID: process.env.REACT_APP_GTM_ID,
  MIN_MESSAGE_LENGTH: process.env.CONTACT_US_MIN_MESSAGE_LENGTH

}
